version: '3.8'
services:
  postgres:
    image: postgres:15.2-alpine
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    volumes:
      - family-tree-api-postgres-volume:/var/lib/postgresql/data
      - ./hack/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DATABASES: "familytree"
      POSTGRES_PASSWORD: "postgres"

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: dracula
    ports:
      - 8081:8080

volumes:
  family-tree-api-postgres-volume: null
